export interface County {
  name: string;
  slug: string;
  seat: string;
  population: number;
  top20: boolean;
}

// 2020 census population; top20 flag marks the 20 most populous
export const counties: County[] = [
  { name: 'Appling', slug: 'appling', seat: 'Baxley', population: 18386, top20: false },
  { name: 'Atkinson', slug: 'atkinson', seat: 'Pearson', population: 8286, top20: false },
  { name: 'Bacon', slug: 'bacon', seat: 'Alma', population: 11140, top20: false },
  { name: 'Baker', slug: 'baker', seat: 'Newton', population: 2876, top20: false },
  { name: 'Baldwin', slug: 'baldwin', seat: 'Milledgeville', population: 43799, top20: false },
  { name: 'Banks', slug: 'banks', seat: 'Homer', population: 19234, top20: false },
  { name: 'Barrow', slug: 'barrow', seat: 'Winder', population: 83505, top20: false },
  { name: 'Bartow', slug: 'bartow', seat: 'Cartersville', population: 108901, top20: false },
  { name: 'Ben Hill', slug: 'ben-hill', seat: 'Fitzgerald', population: 16700, top20: false },
  { name: 'Berrien', slug: 'berrien', seat: 'Nashville', population: 18201, top20: false },
  { name: 'Bibb', slug: 'bibb', seat: 'Macon', population: 157346, top20: true },
  { name: 'Bleckley', slug: 'bleckley', seat: 'Cochran', population: 12623, top20: false },
  { name: 'Brantley', slug: 'brantley', seat: 'Nahunta', population: 18021, top20: false },
  { name: 'Brooks', slug: 'brooks', seat: 'Quitman', population: 16243, top20: false },
  { name: 'Bryan', slug: 'bryan', seat: 'Pembroke', population: 44738, top20: false },
  { name: 'Bulloch', slug: 'bulloch', seat: 'Statesboro', population: 81099, top20: false },
  { name: 'Burke', slug: 'burke', seat: 'Waynesboro', population: 24596, top20: false },
  { name: 'Butts', slug: 'butts', seat: 'Jackson', population: 25434, top20: false },
  { name: 'Calhoun', slug: 'calhoun', seat: 'Morgan', population: 5573, top20: false },
  { name: 'Camden', slug: 'camden', seat: 'Woodbine', population: 54768, top20: false },
  { name: 'Candler', slug: 'candler', seat: 'Metter', population: 10981, top20: false },
  { name: 'Carroll', slug: 'carroll', seat: 'Carrollton', population: 119148, top20: true },
  { name: 'Catoosa', slug: 'catoosa', seat: 'Ringgold', population: 67580, top20: false },
  { name: 'Charlton', slug: 'charlton', seat: 'Folkston', population: 12518, top20: false },
  { name: 'Chatham', slug: 'chatham', seat: 'Savannah', population: 295291, top20: true },
  { name: 'Chattahoochee', slug: 'chattahoochee', seat: 'Cusseta', population: 9565, top20: false },
  { name: 'Chattooga', slug: 'chattooga', seat: 'Summerville', population: 24965, top20: false },
  { name: 'Cherokee', slug: 'cherokee', seat: 'Canton', population: 266620, top20: true },
  { name: 'Clarke', slug: 'clarke', seat: 'Athens', population: 128331, top20: false },
  { name: 'Clay', slug: 'clay', seat: 'Fort Gaines', population: 2848, top20: false },
  { name: 'Clayton', slug: 'clayton', seat: 'Jonesboro', population: 297595, top20: true },
  { name: 'Clinch', slug: 'clinch', seat: 'Homerville', population: 6798, top20: false },
  { name: 'Cobb', slug: 'cobb', seat: 'Marietta', population: 766149, top20: true },
  { name: 'Coffee', slug: 'coffee', seat: 'Douglas', population: 43273, top20: false },
  { name: 'Colquitt', slug: 'colquitt', seat: 'Moultrie', population: 45898, top20: false },
  { name: 'Columbia', slug: 'columbia', seat: 'Evans', population: 156010, top20: true },
  { name: 'Cook', slug: 'cook', seat: 'Adel', population: 17229, top20: false },
  { name: 'Coweta', slug: 'coweta', seat: 'Newnan', population: 146158, top20: true },
  { name: 'Crawford', slug: 'crawford', seat: 'Roberta', population: 12130, top20: false },
  { name: 'Crisp', slug: 'crisp', seat: 'Cordele', population: 22372, top20: false },
  { name: 'Dade', slug: 'dade', seat: 'Trenton', population: 16251, top20: false },
  { name: 'Dawson', slug: 'dawson', seat: 'Dawsonville', population: 26798, top20: false },
  { name: 'Decatur', slug: 'decatur', seat: 'Bainbridge', population: 29367, top20: false },
  { name: 'DeKalb', slug: 'dekalb', seat: 'Decatur', population: 764382, top20: true },
  { name: 'Dodge', slug: 'dodge', seat: 'Eastman', population: 20951, top20: false },
  { name: 'Dooly', slug: 'dooly', seat: 'Vienna', population: 11208, top20: false },
  { name: 'Dougherty', slug: 'dougherty', seat: 'Albany', population: 88465, top20: false },
  { name: 'Douglas', slug: 'douglas', seat: 'Douglasville', population: 144237, top20: true },
  { name: 'Early', slug: 'early', seat: 'Blakely', population: 10190, top20: false },
  { name: 'Echols', slug: 'echols', seat: 'Statenville', population: 3697, top20: false },
  { name: 'Effingham', slug: 'effingham', seat: 'Springfield', population: 64769, top20: false },
  { name: 'Elbert', slug: 'elbert', seat: 'Elberton', population: 19637, top20: false },
  { name: 'Emanuel', slug: 'emanuel', seat: 'Swainsboro', population: 22768, top20: false },
  { name: 'Evans', slug: 'evans', seat: 'Claxton', population: 10654, top20: false },
  { name: 'Fannin', slug: 'fannin', seat: 'Blue Ridge', population: 25319, top20: false },
  { name: 'Fayette', slug: 'fayette', seat: 'Fayetteville', population: 119194, top20: true },
  { name: 'Floyd', slug: 'floyd', seat: 'Rome', population: 98498, top20: false },
  { name: 'Forsyth', slug: 'forsyth', seat: 'Cumming', population: 251283, top20: true },
  { name: 'Franklin', slug: 'franklin', seat: 'Carnesville', population: 23424, top20: false },
  { name: 'Fulton', slug: 'fulton', seat: 'Atlanta', population: 1066710, top20: true },
  { name: 'Gilmer', slug: 'gilmer', seat: 'Ellijay', population: 31369, top20: false },
  { name: 'Glascock', slug: 'glascock', seat: 'Gibson', population: 2884, top20: false },
  { name: 'Glynn', slug: 'glynn', seat: 'Brunswick', population: 85292, top20: false },
  { name: 'Gordon', slug: 'gordon', seat: 'Calhoun', population: 57963, top20: false },
  { name: 'Grady', slug: 'grady', seat: 'Cairo', population: 26236, top20: false },
  { name: 'Greene', slug: 'greene', seat: 'Greensboro', population: 18915, top20: false },
  { name: 'Gwinnett', slug: 'gwinnett', seat: 'Lawrenceville', population: 957062, top20: true },
  { name: 'Habersham', slug: 'habersham', seat: 'Clarkesville', population: 46031, top20: false },
  { name: 'Hall', slug: 'hall', seat: 'Gainesville', population: 203136, top20: true },
  { name: 'Hancock', slug: 'hancock', seat: 'Sparta', population: 8460, top20: false },
  { name: 'Haralson', slug: 'haralson', seat: 'Buchanan', population: 29791, top20: false },
  { name: 'Harris', slug: 'harris', seat: 'Hamilton', population: 35236, top20: false },
  { name: 'Hart', slug: 'hart', seat: 'Hartwell', population: 25897, top20: false },
  { name: 'Heard', slug: 'heard', seat: 'Franklin', population: 11412, top20: false },
  { name: 'Henry', slug: 'henry', seat: 'McDonough', population: 240712, top20: true },
  { name: 'Houston', slug: 'houston', seat: 'Perry', population: 163633, top20: true },
  { name: 'Irwin', slug: 'irwin', seat: 'Ocilla', population: 9666, top20: false },
  { name: 'Jackson', slug: 'jackson', seat: 'Jefferson', population: 75907, top20: false },
  { name: 'Jasper', slug: 'jasper', seat: 'Monticello', population: 14430, top20: false },
  { name: 'Jeff Davis', slug: 'jeff-davis', seat: 'Hazlehurst', population: 14808, top20: false },
  { name: 'Jefferson', slug: 'jefferson', seat: 'Louisville', population: 15709, top20: false },
  { name: 'Jenkins', slug: 'jenkins', seat: 'Millen', population: 8674, top20: false },
  { name: 'Johnson', slug: 'johnson', seat: 'Wrightsville', population: 9306, top20: false },
  { name: 'Jones', slug: 'jones', seat: 'Gray', population: 28347, top20: false },
  { name: 'Lamar', slug: 'lamar', seat: 'Barnesville', population: 18317, top20: false },
  { name: 'Lanier', slug: 'lanier', seat: 'Lakeland', population: 9877, top20: false },
  { name: 'Laurens', slug: 'laurens', seat: 'Dublin', population: 49427, top20: false },
  { name: 'Lee', slug: 'lee', seat: 'Leesburg', population: 33163, top20: false },
  { name: 'Liberty', slug: 'liberty', seat: 'Hinesville', population: 65256, top20: false },
  { name: 'Lincoln', slug: 'lincoln', seat: 'Lincolnton', population: 7690, top20: false },
  { name: 'Long', slug: 'long', seat: 'Ludowici', population: 16168, top20: false },
  { name: 'Lowndes', slug: 'lowndes', seat: 'Valdosta', population: 118251, top20: false },
  { name: 'Lumpkin', slug: 'lumpkin', seat: 'Dahlonega', population: 33610, top20: false },
  { name: 'Macon', slug: 'macon', seat: 'Oglethorpe', population: 12082, top20: false },
  { name: 'Madison', slug: 'madison', seat: 'Danielsville', population: 30120, top20: false },
  { name: 'Marion', slug: 'marion', seat: 'Buena Vista', population: 7498, top20: false },
  { name: 'McDuffie', slug: 'mcduffie', seat: 'Thomson', population: 21184, top20: false },
  { name: 'McIntosh', slug: 'mcintosh', seat: 'Darien', population: 10975, top20: false },
  { name: 'Meriwether', slug: 'meriwether', seat: 'Greenville', population: 20614, top20: false },
  { name: 'Miller', slug: 'miller', seat: 'Colquitt', population: 5718, top20: false },
  { name: 'Mitchell', slug: 'mitchell', seat: 'Camilla', population: 21756, top20: false },
  { name: 'Monroe', slug: 'monroe', seat: 'Forsyth', population: 27957, top20: false },
  { name: 'Montgomery', slug: 'montgomery', seat: 'Mount Vernon', population: 8610, top20: false },
  { name: 'Morgan', slug: 'morgan', seat: 'Madison', population: 20097, top20: false },
  { name: 'Murray', slug: 'murray', seat: 'Chatsworth', population: 39973, top20: false },
  { name: 'Muscogee', slug: 'muscogee', seat: 'Columbus', population: 206922, top20: true },
  { name: 'Newton', slug: 'newton', seat: 'Covington', population: 112483, top20: false },
  { name: 'Oconee', slug: 'oconee', seat: 'Watkinsville', population: 41799, top20: false },
  { name: 'Oglethorpe', slug: 'oglethorpe', seat: 'Lexington', population: 14899, top20: false },
  { name: 'Paulding', slug: 'paulding', seat: 'Dallas', population: 168667, top20: true },
  { name: 'Peach', slug: 'peach', seat: 'Fort Valley', population: 27981, top20: false },
  { name: 'Pickens', slug: 'pickens', seat: 'Jasper', population: 33246, top20: false },
  { name: 'Pierce', slug: 'pierce', seat: 'Blackshear', population: 19716, top20: false },
  { name: 'Pike', slug: 'pike', seat: 'Zebulon', population: 18937, top20: false },
  { name: 'Polk', slug: 'polk', seat: 'Cedartown', population: 42854, top20: false },
  { name: 'Pulaski', slug: 'pulaski', seat: 'Hawkinsville', population: 9855, top20: false },
  { name: 'Putnam', slug: 'putnam', seat: 'Eatonton', population: 22047, top20: false },
  { name: 'Quitman', slug: 'quitman', seat: 'Georgetown', population: 2235, top20: false },
  { name: 'Rabun', slug: 'rabun', seat: 'Clayton', population: 16883, top20: false },
  { name: 'Randolph', slug: 'randolph', seat: 'Cuthbert', population: 6425, top20: false },
  { name: 'Richmond', slug: 'richmond', seat: 'Augusta', population: 206607, top20: true },
  { name: 'Rockdale', slug: 'rockdale', seat: 'Conyers', population: 93570, top20: false },
  { name: 'Schley', slug: 'schley', seat: 'Ellaville', population: 4547, top20: false },
  { name: 'Screven', slug: 'screven', seat: 'Sylvania', population: 13966, top20: false },
  { name: 'Seminole', slug: 'seminole', seat: 'Donalsonville', population: 8218, top20: false },
  { name: 'Spalding', slug: 'spalding', seat: 'Griffin', population: 66980, top20: false },
  { name: 'Stephens', slug: 'stephens', seat: 'Toccoa', population: 26175, top20: false },
  { name: 'Stewart', slug: 'stewart', seat: 'Lumpkin', population: 5314, top20: false },
  { name: 'Sumter', slug: 'sumter', seat: 'Americus', population: 29616, top20: false },
  { name: 'Talbot', slug: 'talbot', seat: 'Talbotton', population: 5733, top20: false },
  { name: 'Taliaferro', slug: 'taliaferro', seat: 'Crawfordville', population: 1559, top20: false },
  { name: 'Tattnall', slug: 'tattnall', seat: 'Reidsville', population: 22842, top20: false },
  { name: 'Taylor', slug: 'taylor', seat: 'Butler', population: 7805, top20: false },
  { name: 'Telfair', slug: 'telfair', seat: 'McRae-Helena', population: 12477, top20: false },
  { name: 'Terrell', slug: 'terrell', seat: 'Dawson', population: 8531, top20: false },
  { name: 'Thomas', slug: 'thomas', seat: 'Thomasville', population: 45798, top20: false },
  { name: 'Tift', slug: 'tift', seat: 'Tifton', population: 41266, top20: false },
  { name: 'Toombs', slug: 'toombs', seat: 'Lyons', population: 26830, top20: false },
  { name: 'Towns', slug: 'towns', seat: 'Hiawassee', population: 12493, top20: false },
  { name: 'Treutlen', slug: 'treutlen', seat: 'Soperton', population: 6406, top20: false },
  { name: 'Troup', slug: 'troup', seat: 'LaGrange', population: 69426, top20: false },
  { name: 'Turner', slug: 'turner', seat: 'Ashburn', population: 8791, top20: false },
  { name: 'Twiggs', slug: 'twiggs', seat: 'Jeffersonville', population: 7818, top20: false },
  { name: 'Union', slug: 'union', seat: 'Blairsville', population: 24632, top20: false },
  { name: 'Upson', slug: 'upson', seat: 'Thomaston', population: 27485, top20: false },
  { name: 'Walker', slug: 'walker', seat: 'LaFayette', population: 67654, top20: false },
  { name: 'Walton', slug: 'walton', seat: 'Monroe', population: 96673, top20: false },
  { name: 'Ware', slug: 'ware', seat: 'Waycross', population: 35734, top20: false },
  { name: 'Warren', slug: 'warren', seat: 'Warrenton', population: 5215, top20: false },
  { name: 'Washington', slug: 'washington', seat: 'Sandersville', population: 19969, top20: false },
  { name: 'Wayne', slug: 'wayne', seat: 'Jesup', population: 30289, top20: false },
  { name: 'Webster', slug: 'webster', seat: 'Preston', population: 2486, top20: false },
  { name: 'Wheeler', slug: 'wheeler', seat: 'Alamo', population: 7471, top20: false },
  { name: 'White', slug: 'white', seat: 'Cleveland', population: 28003, top20: false },
  { name: 'Whitfield', slug: 'whitfield', seat: 'Dalton', population: 102864, top20: false },
  { name: 'Wilcox', slug: 'wilcox', seat: 'Abbeville', population: 8766, top20: false },
  { name: 'Wilkes', slug: 'wilkes', seat: 'Washington', population: 9565, top20: false },
  { name: 'Wilkinson', slug: 'wilkinson', seat: 'Irwinton', population: 8913, top20: false },
  { name: 'Worth', slug: 'worth', seat: 'Sylvester', population: 20247, top20: false },
];

export function slugifyCounty(name: string): string {
  return name
    .replace(/\s+County\s*$/i, '')
    .toLowerCase()
    .trim()
    .replace(/\s+/g, '-');
}

export function getCountyBySlug(slug: string): County | undefined {
  return counties.find((c) => c.slug === slug);
}

export function getCountyByName(name: string): County | undefined {
  const slug = slugifyCounty(name);
  return counties.find((c) => c.slug === slug);
}

export const top20Counties = counties.filter((c) => c.top20);
